// ActionType과 RoleType의 한국어 표시명 매핑

import type { ActionType, RoleType } from '@/features/prompt/types';

// ActionType 한국어 표시명 매핑
export const ACTION_TYPE_DISPLAY_NAMES_KO: Record<ActionType, string> = {
  // ProductivityActionType
  WORKFLOW_OPTIMIZATION: '워크플로우 최적화',
  TIME_MANAGEMENT: '시간 관리',
  SCHEDULE_PLANNING: '일정 계획',
  DAILY_PLANNING: '하루 계획',
  WEEKLY_PLANNING: '주간 계획',
  MONTHLY_PLANNING: '월간 계획',
  TASK_AUTOMATION: '작업 자동화',
  SHOPPING_LIST: '쇼핑 리스트',
  MEAL_PLANNING: '식사 계획',
  BUDGET_PLANNING: '예산 계획',
  HOUSEHOLD_MANAGEMENT: '가정 관리',
  EFFICIENCY_ANALYSIS: '효율성 분석',
  PRODUCTIVITY_PLANNING: '생산성 계획 수립',
  PROCESS_IMPROVEMENT: '프로세스 개선',
  RESOURCE_OPTIMIZATION: '자원 최적화',
  // DevelopmentActionType
  ARCHITECTURE_DESIGN: '아키텍처 설계',
  SYSTEM_DESIGN: '시스템 설계',
  TECH_STACK_SELECTION: '기술 스택 선택',
  PERFORMANCE_OPTIMIZATION: '성능 최적화',
  DEPLOYMENT_STRATEGY: '배포 전략',
  DOCUMENTATION: '문서화',
  CODEBASE_ANALYSIS: '코드베이스 분석',
  SECURITY_IMPLEMENTATION: '보안 구현',
  SCALABILITY_PLANNING: '확장성 계획',
  // CodingActionType
  CODE_GENERATION: '코드 생성',
  CODE_MODIFICATION: '코드 수정',
  CODE_REVIEW: '코드 리뷰',
  REFACTORING: '리팩토링',
  TEST_GENERATION: '테스트 코드 생성',
  DEBUGGING: '디버깅',
  CODE_ANALYSIS: '코드 분석',
  PATTERN_APPLICATION: '디자인 패턴 적용',
  CODE_OPTIMIZATION: '코드 최적화',
  LEGACY_CODE_MAINTENANCE: '레거시 코드 유지보수',
  // ProgrammingActionType
  ALGORITHM_IMPLEMENTATION: '알고리즘 구현',
  DATA_STRUCTURE_DESIGN: '자료구조 설계',
  LANGUAGE_LEARNING: '언어 학습',
  SYNTAX_OPTIMIZATION: '문법 최적화',
  LOGIC_DEVELOPMENT: '로직 개발',
  API_DESIGN: 'API 설계',
  CONCURRENT_PROGRAMMING: '동시성 프로그래밍',
  // MarketingActionType
  MARKETING_STRATEGY: '마케팅 전략',
  BRANDING: '브랜딩',
  AD_CAMPAIGN: '광고 캠페인',
  MARKET_RESEARCH: '시장 조사',
  CUSTOMER_ANALYSIS: '고객 분석',
  SEO_OPTIMIZATION: 'SEO 최적화',
  SOCIAL_MEDIA_STRATEGY: '소셜 미디어 전략',
  CONTENT_MARKETING: '콘텐츠 마케팅',
  INFLUENCER_MARKETING: '인플루언서 마케팅',
  CONVERSION_OPTIMIZATION: '전환 최적화',
  // CreativeActionType
  IDEA_GENERATION: '아이디어 생성',
  CREATIVE_WRITING: '창작 글쓰기',
  ARTISTIC_DESIGN: '예술적 디자인',
  STORYTELLING: '스토리텔링',
  CONCEPT_DEVELOPMENT: '컨셉 개발',
  VISUAL_CREATION: '시각적 창작',
  CHARACTER_DEVELOPMENT: '캐릭터 개발',
  WORLD_BUILDING: '세계관 구축',
  // ContentActionType
  CONTENT_CREATION: '콘텐츠 생성',
  CONTENT_REVISION: '콘텐츠 수정',
  CONTENT_PLANNING: '콘텐츠 기획',
  BLOG_WRITING: '블로그 작성',
  SNS_CONTENT: 'SNS 콘텐츠',
  SOCIAL_MEDIA_POST: '소셜 미디어 게시물',
  INSTAGRAM_CAPTION: '인스타그램 캡션',
  FACEBOOK_POST: '페이스북 게시물',
  TWITTER_POST: '트위터 게시물',
  COMMENT_WRITING: '댓글 작성',
  VIDEO_SCRIPT: '영상 스크립트',
  CONTENT_OPTIMIZATION: '콘텐츠 최적화',
  MULTIMEDIA_PRODUCTION: '멀티미디어 제작',
  PODCAST_SCRIPT: '팟캐스트 스크립트',
  NEWSLETTER_WRITING: '뉴스레터 작성',
  // AnalysisActionType
  DATA_ANALYSIS: '데이터 분석',
  STATISTICAL_ANALYSIS: '통계 분석',
  INSIGHT_EXTRACTION: '인사이트 도출',
  TREND_ANALYSIS: '트렌드 분석',
  PATTERN_RECOGNITION: '패턴 인식',
  PREDICTIVE_ANALYSIS: '예측 분석',
  COMPARATIVE_ANALYSIS: '비교 분석',
  ROOT_CAUSE_ANALYSIS: '근본 원인 분석',
  BUSINESS_INTELLIGENCE: '비즈니스 인텔리전스',
  // StudyActionType
  STUDY_PLANNING: '학습 계획',
  NOTE_TAKING: '노트 작성',
  KNOWLEDGE_ORGANIZATION: '지식 정리',
  COMPREHENSION_IMPROVEMENT: '이해력 향상',
  MEMORIZATION_STRATEGY: '암기 전략',
  EXAM_PREPARATION: '시험 준비',
  SKILL_DEVELOPMENT: '기술 개발',
  LEARNING_PATH_DESIGN: '학습 경로 설계',
  QUIZ_GENERATION: '퀴즈 생성',
  // EducationActionType
  CURRICULUM_DESIGN: '교육과정 설계',
  MATERIAL_CREATION: '교육 자료 생성',
  TEACHING_METHOD: '교수법',
  LEARNER_ANALYSIS: '학습자 분석',
  ASSESSMENT_DESIGN: '평가 설계',
  INTERACTIVE_CONTENT: '인터랙티브 콘텐츠',
  EDUCATIONAL_STRATEGY: '교육 전략',
  LESSON_PLANNING: '수업 계획',
  // ResearchActionType
  RESEARCH_DESIGN: '연구 설계',
  PAPER_WRITING: '논문 작성',
  METHODOLOGY_DEVELOPMENT: '방법론 개발',
  EXPERIMENT_DESIGN: '실험 설계',
  DATA_INTERPRETATION: '데이터 해석',
  LITERATURE_REVIEW: '문헌 리뷰',
  HYPOTHESIS_FORMULATION: '가설 수립',
  STATISTICAL_MODELING: '통계 모델링',
  // BusinessActionType
  PROPOSAL_WRITING: '기획서 작성',
  REPORT_WRITING: '보고서 작성',
  BUSINESS_STRATEGY: '사업 전략',
  PROJECT_MANAGEMENT: '프로젝트 관리',
  FINANCIAL_ANALYSIS: '재무 분석',
  PRESENTATION_PREPARATION: '발표 자료 준비',
  CONTRACT_REVIEW: '계약 검토',
  RISK_ASSESSMENT: '리스크 평가',
  STAKEHOLDER_MANAGEMENT: '이해관계자 관리',
  BUSINESS_PLAN_DEVELOPMENT: '사업계획서 개발',
  // DesignActionType
  UI_DESIGN: 'UI 디자인',
  UX_DESIGN: 'UX 디자인',
  GRAPHIC_DESIGN: '그래픽 디자인',
  PRODUCT_DESIGN: '제품 디자인',
  DESIGN_DOC: '설계 문서',
  WIREFRAMING: '와이어프레임',
  PROTOTYPING: '프로토타이핑',
  VISUAL_IDENTITY: '비주얼 아이덴티티',
  INTERACTION_DESIGN: '인터랙션 디자인',
  RESPONSIVE_DESIGN: '반응형 디자인',
  // WritingActionType
  ARTICLE_WRITING: '기사 작성',
  ESSAY_WRITING: '에세이 작성',
  TECHNICAL_WRITING: '기술 문서 작성',
  CREATIVE_WRITING_GEN: '창작 글쓰기',
  EDITING: '편집',
  PROOFREADING: '교정',
  TRANSLATION: '번역',
  DOC_UPDATE: '문서 업데이트',
  COPYWRITING: '카피라이팅',
  GRANT_WRITING: '기획안 작성',
  LETTER_WRITING: '편지 작성',
  PERSONAL_LETTER: '개인 편지',
  BUSINESS_LETTER: '공식 편지',
  INVITATION_CARD: '초대장 작성',
  THANK_YOU_CARD: '감사 카드',
  CONGRATULATORY_MESSAGE: '축하 메시지',
  CONDOLENCE_MESSAGE: '조의 메시지',
  MESSAGE_WRITING: '메시지 작성',
  TEXT_MESSAGE: '문자 메시지',
  WHATSAPP_MESSAGE: '왓츠앱 메시지',
  // EtcActionType
  GENERAL_CONSULTATION: '일반 상담',
  PROBLEM_SOLVING: '문제 해결',
  INFORMATION_RESEARCH: '정보 조사',
  RECOMMENDATION: '추천',
  EXPLANATION: '설명',
  ADVICE: '조언',
  GUIDANCE: '안내',
  RECIPE_CREATION: '레시피 작성',
  COOKING_TIPS: '요리 팁',
  HEALTH_MANAGEMENT: '건강 관리',
  // SocialActionType
  COMMUNITY_ENGAGEMENT: '커뮤니티 참여',
  EVENT_ORGANIZATION: '이벤트 조직',
  SOCIAL_CAUSE_SUPPORT: '사회적 원인 지원',
  VOLUNTEER_COORDINATION: '자원봉사 조정',
  FUNDRAISING: '모금',
  COMMUNITY_OUTREACH: '커뮤니티 외부 연계',
  SOCIAL_MEDIA_ENGAGEMENT: '소셜 미디어 참여',
  NETWORKING_EVENT: '네트워킹 이벤트',
  COMMUNITY_BUILDING: '커뮤니티 구축',
  SOCIAL_ACTIVISM: '사회 운동',
  ADVOCACY: '옹호 활동',
  PUBLIC_SPEAKING: '공개 연설',
  SOCIAL_IMPACT: '사회적 영향',
  COLLABORATION: '협업',
  PARTNERSHIP_BUILDING: '파트너십 구축',
  CROSS_CULTURAL_COMMUNICATION: '문화 간 소통',
  TRAVEL_PLANNING: '여행 계획',
  EVENT_PLANNING: '행사 기획',
  PARTY_PLANNING: '파티 기획',
  GIFT_SELECTION: '선물 선택',
  DECORATION_IDEAS: '장식 아이디어',
  HOME_ORGANIZATION: '집 정리',
  CHILD_CARE_TIPS: '육아 팁',
  EDUCATION_CONSULTATION: '교육 상담',
  RELATIONSHIP_ADVICE: '관계 조언',
  CONFLICT_RESOLUTION: '갈등 해결',
  DECISION_MAKING: '의사결정',
  GOAL_SETTING: '목표 설정',
  HABIT_FORMATION: '습관 형성',
  MOTIVATION: '동기 부여',
  SELF_IMPROVEMENT: '자기계발',
  STRESS_MANAGEMENT: '스트레스 관리',
  TIME_OFF_PLANNING: '휴가 계획',
  HOBBY_EXPLORATION: '취미 탐색',
  BOOK_RECOMMENDATION: '도서 추천',
  MOVIE_RECOMMENDATION: '영화 추천',
  RESTAURANT_RECOMMENDATION: '맛집 추천',
  PRODUCT_REVIEW: '제품 리뷰',
  COMPARISON_SHOPPING: '상품 비교',
  PRICE_NEGOTIATION: '가격 협상',
  COMPLAINT_WRITING: '불만 접수',
  FEEDBACK_WRITING: '피드백 작성',
  REVIEW_WRITING: '리뷰 작성',
  TESTIMONIAL_WRITING: '추천서 작성',
  APPLICATION_WRITING: '지원서 작성',
  RESUME_WRITING: '이력서 작성',
  COVER_LETTER: '자기소개서',
  INTERVIEW_PREPARATION: '면접 준비',
  NETWORKING_MESSAGE: '네트워킹 메시지',
  FOLLOW_UP_MESSAGE: '후속 메시지',
  APPOINTMENT_SCHEDULING: '약속 잡기',
  REMINDER_MESSAGE: '알림 메시지',
  BIRTHDAY_MESSAGE: '생일 메시지',
  ANNIVERSARY_MESSAGE: '기념일 메시지',
  HOLIDAY_GREETING: '명절 인사',
  SEASONAL_GREETING: '계절 인사',
  // HealthFitnessActionType
  WORKOUT_PLANS: '운동 계획',
  NUTRITION_TRACKING: '영양 추적',
  MEDICAL_RECORD_MANAGEMENT: '의료 기록 관리',
  FITNESS_GOAL_SETTING: '피트니스 목표 설정',
  EXERCISE_PLANNING: '운동 계획',
  DIET_PLANNING: '식단 계획',
  WEIGHT_MANAGEMENT: '체중 관리',
  CARDIO_TRAINING: '유산소 운동',
  STRENGTH_TRAINING: '근력 운동',
  FLEXIBILITY_TRAINING: '유연성 운동',
  RECOVERY_PLANNING: '회복 계획',
  NUTRITION_PLANNING: '영양 계획',
  MEAL_PREP: '식사 준비',
  SUPPLEMENT_GUIDANCE: '보조제 가이드',
  HEALTH_SCREENING: '건강 검진',
  CHRONIC_DISEASE_MANAGEMENT: '만성 질환 관리',
  MENTAL_HEALTH: '정신 건강',
  SLEEP_OPTIMIZATION: '수면 최적화',
  STRESS_MANAGEMENT_HEALTH: '스트레스 관리',
  FITNESS_TRACKING: '피트니스 추적',
  WORKOUT_FORM_CORRECTION: '운동 자세 교정',
  // CustomerSupportActionType
  TICKET_CREATION: '티켓 생성',
  TICKET_RESOLUTION: '티켓 해결',
  KNOWLEDGE_BASE_MANAGEMENT: '지식 기반 관리',
  LIVE_CHAT_SUPPORT: '실시간 채팅 지원',
  CUSTOMER_SERVICE: '고객 서비스',
  FAQ_CREATION: 'FAQ 작성',
  SUPPORT_DOCUMENTATION: '지원 문서화',
  CUSTOMER_ONBOARDING: '고객 온보딩',
  CUSTOMER_RETENTION: '고객 유지',
  COMPLAINT_HANDLING: '불만 처리',
  CUSTOMER_FEEDBACK_ANALYSIS: '고객 피드백 분석',
  SUPPORT_TRAINING: '지원 교육',
  REMOTE_SUPPORT: '원격 지원',
  CUSTOMER_SATISFACTION: '고객 만족도',
  EMAIL_WRITING: '이메일 작성',
  BUSINESS_EMAIL: '비즈니스 이메일',
  PERSONAL_EMAIL: '개인 이메일',
  THANK_YOU_EMAIL: '감사 이메일',
  APOLOGY_EMAIL: '사과 이메일',
  INQUIRY_EMAIL: '문의 이메일',
  INVITATION_EMAIL: '초대 이메일',
  FOLLOW_UP_EMAIL: '후속 이메일',
  REJECTION_EMAIL: '거절 이메일',
  CONFIRMATION_EMAIL: '확인 이메일',
  // AiMlActionType
  MODEL_TRAINING: '모델 훈련',
  PREDICTION: '예측',
  DATA_PREPROCESSING: '데이터 전처리',
  MODEL_EVALUATION: '모델 평가',
  HYPERPARAMETER_TUNING: '하이퍼파라미터 조정',
  FEATURE_ENGINEERING: '특성 공학',
  MODEL_SELECTION: '모델 선택',
  DEEP_LEARNING: '딥러닝',
  NEURAL_NETWORK_DESIGN: '신경망 설계',
  TRANSFER_LEARNING: '전이 학습',
  REINFORCEMENT_LEARNING: '강화 학습',
  NATURAL_LANGUAGE_PROCESSING: '자연어 처리',
  COMPUTER_VISION: '컴퓨터 비전',
  MODEL_DEPLOYMENT: '모델 배포',
  MODEL_MONITORING: '모델 모니터링',
  A_B_TESTING: 'A/B 테스트',
  DATA_LABELING: '데이터 라벨링',
  MODEL_OPTIMIZATION: '모델 최적화',
  EXPLAINABLE_AI: '설명 가능한 AI',
  // CybersecurityActionType
  VULNERABILITY_SCANNING: '취약점 스캐닝',
  PENETRATION_TESTING: '침투 테스트',
  THREAT_ANALYSIS: '위협 분석',
  DATA_ENCRYPTION: '데이터 암호화',
  SECURITY_AUDIT: '보안 감사',
  INCIDENT_RESPONSE: '사고 대응',
  SECURITY_POLICY: '보안 정책',
  ACCESS_CONTROL: '접근 제어',
  IDENTITY_MANAGEMENT: '신원 관리',
  NETWORK_SECURITY: '네트워크 보안',
  APPLICATION_SECURITY: '애플리케이션 보안',
  SECURITY_TRAINING: '보안 교육',
  RISK_ASSESSMENT_SECURITY: '보안 위험 평가',
  COMPLIANCE_MANAGEMENT: '규정 준수 관리',
  SECURITY_MONITORING: '보안 모니터링',
  MALWARE_ANALYSIS: '멀웨어 분석',
  FIREWALL_CONFIGURATION: '방화벽 구성',
  // DevOpsActionType
  CI_CD_PIPELINE: 'CI/CD 파이프라인',
  AUTOMATED_TESTING: '자동화 테스트',
  INTEGRATION_TESTING: '통합 테스트',
  INFRASTRUCTURE_AS_CODE: '코드로서의 인프라',
  CONTINUOUS_INTEGRATION: '지속적 통합',
  CONTINUOUS_DEPLOYMENT: '지속적 배포',
  CONTINUOUS_DELIVERY: '지속적 전달',
  CONTAINERIZATION: '컨테이너화',
  DOCKER_SETUP: 'Docker 설정',
  KUBERNETES_ORCHESTRATION: 'Kubernetes 오케스트레이션',
  CONFIGURATION_MANAGEMENT: '구성 관리',
  VERSION_CONTROL: '버전 관리',
  DEPLOYMENT_STRATEGY_DEVOPS: '배포 전략',
  MONITORING_ALERTING: '모니터링 및 알림',
  LOG_MANAGEMENT: '로그 관리',
  PERFORMANCE_MONITORING: '성능 모니터링',
  INFRASTRUCTURE_MONITORING: '인프라 모니터링',
  // CloudServicesActionType
  CLOUD_DEPLOYMENT: '클라우드 배포',
  CLOUD_SECURITY: '클라우드 보안',
  CLOUD_MONITORING: '클라우드 모니터링',
  CLOUD_MIGRATION: '클라우드 마이그레이션',
  AWS_ARCHITECTURE: 'AWS 아키텍처',
  AZURE_SETUP: 'Azure 설정',
  GCP_CONFIGURATION: 'GCP 구성',
  CONTAINER_ORCHESTRATION: '컨테이너 오케스트레이션',
  SERVERLESS_ARCHITECTURE: '서버리스 아키텍처',
  CLOUD_COST_OPTIMIZATION: '클라우드 비용 최적화',
  DISASTER_RECOVERY: '재해 복구',
  CLOUD_BACKUP: '클라우드 백업',
  LOAD_BALANCING: '로드 밸런싱',
  AUTO_SCALING: '자동 스케일링',
  CLOUD_NETWORKING: '클라우드 네트워킹',
};

// RoleType 한국어 표시명 매핑
export const ROLE_TYPE_DISPLAY_NAMES_KO: Record<RoleType, string> = {
  // ProductivityRoleType
  PRODUCTIVITY_EXPERT: '생산성 전문가',
  // DevelopmentRoleType
  BACKEND_DEVELOPER: '백엔드 개발자',
  FRONTEND_DEVELOPER: '프론트엔드 개발자',
  FULL_STACK_DEVELOPER: '풀스택 개발자',
  DEVOPS_ENGINEER: 'DevOps 엔지니어',
  CLOUD_ARCHITECT: '클라우드 아키텍트',
  SITE_RELIABILITY_ENGINEER: 'SRE 엔지니어',
  // MarketingRoleType
  MARKETING_STRATEGIST: '마케팅 전략가',
  BRAND_SPECIALIST: '브랜드 전문가',
  DIGITAL_MARKETER: '디지털 마케터',
  // CreativeRoleType
  CREATIVE_DIRECTOR: '크리에이티브 디렉터',
  STORYTELLER: '스토리텔러',
  CONCEPT_ARTIST: '컨셉 아티스트',
  // ContentRoleType
  CONTENT_CREATOR: '콘텐츠 제작자',
  CONTENT_STRATEGIST: '콘텐츠 전략가',
  SOCIAL_MEDIA_MANAGER: '소셜 미디어 매니저',
  // StudyRoleType
  STUDY_COACH: '학습 코치',
  LEARNING_SPECIALIST: '학습 전문가',
  TUTOR: '튜터',
  // EducationRoleType
  EDUCATOR: '교육자',
  CURRICULUM_DESIGNER: '교육과정 설계자',
  INSTRUCTIONAL_DESIGNER: '교수 설계자',
  // ResearchRoleType
  RESEARCHER: '연구자',
  ACADEMIC_WRITER: '학술 논문 작성자',
  RESEARCH_METHODOLOGIST: '연구 방법론 전문가',
  // BusinessRoleType
  BUSINESS_CONSULTANT: '비즈니스 컨설턴트',
  PROJECT_MANAGER: '프로젝트 매니저',
  BUSINESS_ANALYST_BUSINESS: '비즈니스 분석가',
  FINANCIAL_ANALYST: '재무 분석가',
  // DesignRoleType
  UI_UX_DESIGNER: 'UI/UX 디자이너',
  GRAPHIC_DESIGNER: '그래픽 디자이너',
  PRODUCT_DESIGNER: '제품 디자이너',
  INTERACTION_DESIGNER: '인터랙션 디자이너',
  // WritingRoleType
  TECHNICAL_WRITER: '기술 문서 작성자',
  CONTENT_WRITER: '콘텐츠 작가',
  COPYWRITER: '카피라이터',
  EDITOR: '편집자',
  TRANSLATOR: '번역가',
  // EtcRoleType
  GENERAL_CONSULTANT: '일반 상담 전문가',
  PROBLEM_SOLVER: '문제 해결 전문가',
  INFORMATION_SPECIALIST: '정보 전문가',
  // SocialRoleType
  COMMUNITY_MANAGER: '커뮤니티 매니저',
  EVENT_COORDINATOR: '이벤트 코디네이터',
  SOCIAL_ACTIVIST: '사회 운동가',
  VOLUNTEER_COORDINATOR: '자원봉사 코디네이터',
  FUNDRAISING_SPECIALIST: '모금 전문가',
  PUBLIC_RELATIONS_SPECIALIST: 'PR 전문가',
  // HealthFitnessRoleType
  FITNESS_COACH: '피트니스 코치',
  NUTRITIONIST: '영양사',
  PERSONAL_TRAINER: '개인 트레이너',
  WELLNESS_COACH: '웰니스 코치',
  HEALTH_EDUCATOR: '건강 교육자',
  // CustomerSupportRoleType
  CUSTOMER_SUPPORT_SPECIALIST: '고객 지원 전문가',
  CUSTOMER_SUCCESS_MANAGER: '고객 성공 관리자',
  TECHNICAL_SUPPORT_ENGINEER: '기술 지원 엔지니어',
  SUPPORT_TRAINER: '지원 교육 전문가',
  // AiMlRoleType
  ML_ENGINEER: '머신러닝 엔지니어',
  DATA_SCIENTIST: '데이터 사이언티스트',
  AI_RESEARCHER: 'AI 연구원',
  NLP_SPECIALIST: '자연어 처리 전문가',
  COMPUTER_VISION_ENGINEER: '컴퓨터 비전 엔지니어',
  // CybersecurityRoleType
  SECURITY_ENGINEER: '보안 엔지니어',
  PENETRATION_TESTER: '침투 테스트 전문가',
  SECURITY_ANALYST: '보안 분석가',
  INFORMATION_SECURITY_OFFICER: '정보 보안 담당자',
};

